### PR TITLE
WMC Tool v1.4 - automatic instrumentation of speech and audio codecs …

### PR DESCRIPTION
**Pull request by malenov**
On behalf of VoiceAge Corp. I'd like to ask you to integrate the WMC Tool. The WMC tool allows for automatic complexity and memory instrumentation of speech and audio codecs written in the floating point format.

### CODE REVIEW

**Comment by ludomal** [comment]
@malenov, thank you very much for your contribution. 
I have tried to compile the project and `cmake .` returns the following error:

```
CMake Error at src/wmc_tool/CMakeLists.txt:54 (add_executable):

No SOURCES given to target: wmc_tool
```

It returns this error on both macOS and Ubuntu. Does it compile on your end?

**Comment by malenov** [comment]
Dear Ludovic, thank you for your review. I have fixed the cmake issues. Can you re-try, please?

**Comment by ludomal** [comment]
@malenov , I apologize for the late response, I did not receive the notification for your message. I confirm it compiles on both macOS and Linux (Ubuntu).

The test do not seem to execute on macOS or Linux, as the script does not find the path `./STL/test_data`:

```
The following tests FAILED:
	1135 - Test_Single_File (Not Run)
	1136 - Test_Single_File2 (Not Run)
	1137 - Test_Multiple_Files (Not Run)
	1138 - Test_Basop_File (Not Run)
	1139 - Test_Basop_File2 (Not Run)
	1140 - Test_ROM_File (Not Run)
	1141 - Test_ROM_File2 (Not Run)
	1142 - Test_Desinstrument_File (Not Run)
	1143 - Test_Desinstrument_ROM_File (Not Run)
```

**Comment by malenov** [comment]
@ludomal , thank you for your review. I have corrected the path in add_test(.). It shouuld now run all tests when ctest is invoked from the top-level directory.

**Comment by ludomal** [comment]
@malenov, I have added some Latex documentation for the Manual. Would you be able to review and add where necessary?

I would also like to add an example of output for `print_wmops()` and `print_mem()`. 
I have tried to compile `test_data/ref/main1.c` as an example, but `test_data/ref/wmc_auto.c` includes `"options.h"` which is missing from the repository.

Can you check this and provide a print example?

**Comment by malenov** [comment]
Dear @ludomal , thank you for your work. I apologize for not mentioning that I was already working on the complete documentation for the WMC tool. I've seen (too late) that you have already comitted a brief description of the WMC tool as part of the Chapter describing BASOP code. I've now finished a more detailed documentation on the WMC tool and created a separate Chapter for it. I've also provided several examples on how to run the tool and how to interpret the results from the complexity and memory printout. Please, have a look. I did my best to align the formatting and the style with the rest of the documentation.

**Comment by ludomal** [comment]
@malenov, thank you very much for the documentation. I have reviewed it and it looks great; much more detailed than what I could have produced :) I have pushed an update with minor edits.

What does WMC stand for?

Is the package complete from your side?

**Comment by malenov** [comment]
@ludomal , thank you for fixing the typos and correcting the grammar. The package is complete from my side. There may be a future update of the WMC tool based on user experience gathered during the development of the 3GPP IVAS project. Ideally, we would like to reference the WMC tool as part of an official ITU-T release in all technical documents.

WMC stands for `Wmops and Memory Counting` tool :-)

**Comment by ludomal** [comment]
This pull request was integrated in `itu_submission_january_2023` branch, and SG12 consented the update.
The new revision of G.191 - STL2023 is now under [AAP](https://www.itu.int/en/ITU-T/about/Pages/approval.aspx).

The branch will be merged to the main repository in the next few weeks if the revision exits the AAP successfully.

**Pull request merged**
