### PR TITLE
Manual: Updating 2019 manual

### PR DESCRIPTION
**Pull request by ludomal**
This provides:
- The revision of the manual reflecting the new basic operators
- The updates on the text of the Recommendation, as in the published STL2019.

This PR provides a lot of changes. Each commit has details on what has changed and I would like not to lose that information. I would like to do a merge rather than a "squash and merge" on this one.

### CODE REVIEW

**Comment by dennisguse** [comment]
Also looks good to me.
What is the issue with this PR?
Or are there any issues left at all?

**Comment by ludomal** [comment]
All are ok now. There has been some editorial updates made by ITU between the AAP and the publication of the Recommendation. This PR and the Recommendation are now in sync. 

If you are all ok, we can merge this with the Master branch.

**Comment by simaocampos** [comment]
I approved. Not sure the next step
Squash and merge or rebase and merge - as the 1st option is not available.
Simão

[cid:image001.png@01D589A6.A6DD38F0]

**Comment by dennisguse** [comment]
Rebase and merge is fine.
@ludomal Just merge, if you are satisfied :)

**Pull request merged**
