### PR TITLE
modify basop files for EVS codec floating-point source usage

### PR DESCRIPTION
**Pull request by signalogic**
basop32_evs.c and basop32_evs.h are modified basop32 files for use with ETSI 3GPP EVS floating-point source code files that include basop calls. The modifications move some functions to basop32_evs.h as static inline, disable terminations not suitable for Linux libs such as exit() and provide alternate error handling and message logging, and remove or alter use of global variables Overflow and Carry. For example, sub_ovf() is identical to sub() but includes a stack based Overflow param. Definitions such as USE_BASOPS_INLINE, EXCLUDE_BASOPS_NOT_USED_EVS, USE_BASOPS_OVERFLOW_GLOBAL_VAR, USE_BASOPS_CARRY_GLOBAL_VAR, and USE_BASOPS_EXIT allow fine-grain control of modification behavior. Detailed comments are included

### CODE REVIEW

**Comment by dennisguse** [comment]
Let's start simple.
First of all, what is the problem you are solving?
Why should it be included in ITU-T's STL?

Observation:
* This PR duplicates a lot of code (will become a maintenance burden)
I guess, this should be avoided as a cleanup is unlikely to take place.

* There is no test added for this code, right?

* There are code cleanups happening within these commits. Why?

**Comment by signalogic** [comment]
> There are code cleanups happening within these commits. Why?

I assume you mean formatting, indentation, comments, etc ? If so we applied our format rules to be consistent with other codec source files. If you need a version with only functional mods we can provide.

> There is no test added for this code, right?

Right, at least not a minimal functional test. The code is tested extensively as part of our EVS codec, and several reference / test programs that use the codec.

**Comment by simaocampos** [comment]
I suggest keeping the original indentation to facilitate review and minimize surprises.

Indeed the lack of test files has been a systemic problem for this module since the begining when it was first added. But this is mitigated as it is used as part of the code for reference implementation of codecs, so problems could be caught in that context.

Simao

Forgive terseness, composed on a mobile phone.



-------- Original message --------
From: "Signalogic, Inc." ***@***.***>
Date: 3/29/23 21:58 (GMT+01:00)
To: openitu/STL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [openitu/STL] modify basop files for EVS codec floating-point source usage (PR #157)


There are code cleanups happening within these commits. Why?

I assume you mean formatting, indentation, comments, etc ? If so we applied our format rules to be consistent with other codec source files. If you need a version with only functional mods we can provide.

There is no test added for this code, right?

Right, at least not a minimal functional test. The code is tested extensively as part of our EVS codec, and several reference / test programs that use the codec.

**Comment by signalogic** [comment]
Hi Simao, ok we'll resubmit. Should we remove the current pull requests ?

Can we keep the comments ? They are substantial but important in explaining the mods.

**Comment by dennisguse** [comment]
@signalogic you can just overwrite the PR by git push -f

**Comment by simaocampos** [comment]
Thanks for the reply. I think the comments are useful, at least for now.
Simão

**Comment by signalogic** [comment]
updated pull request submitted, with no cleanup on format & indentation

**Pull request closed without merging**
