### PR TITLE
fix some compilation errors on different platforms

### LINKED ISSUE #63: g711, rpelt: cannot be compiled on Windows
OS: Win 10 Pro x64 
Compiled with cmake and Visual Studio 14 2015 

```
"C:\Users\name\STL-dev\ALL_BUILD.vcxproj" (Standardziel) (1) ->
"C:\Users\name\STL-dev\src\unsup\pshar.vcxproj" (Standardziel) (49) ->
(Link Ziel) ->pshar.obj : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "_index" in Funktion "_dounshar". [C:\Users\name\STL-dev\src\unsup\pshar.vcxproj]
C:\Users\name\STL-dev\bin\Debug\pshar.exe : fatal error LNK1120: 1 nicht aufgel÷ste Externe [C:\Users\name\STL-dev\src\unsup\pshar.vcxproj]

"C:\Users\name\STL-dev\ALL_BUILD.vcxproj" (Standardziel) (1) ->
"C:\Users\name\STL-dev\src\g711\shiftbit.vcxproj" (Standardziel) (55) -> (ClCompile Ziel) ->
C:\Users\name\STL-dev\src\g711\shiftbit.c(38): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "unistd.h": No such file or directory [C:\Users\name\STL-dev\src\g711\shiftbit.vcxproj]

"C:\Users\name\STL-dev\ALL_BUILD.vcxproj" (Standardziel) (1) ->
"C:\Users\name\STL-dev\src\rpeltp\test-add.vcxproj" (Standardziel) (62) ->
C:\Users\name\STL-dev\src\rpeltp\add_test.c(14): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "unistd.h": No such file or directory [C:\Users\name\STL-dev\src\rpeltp\test-add.vcxproj]

4318 Warnung(en)
4 Fehler
```

### PR DESCRIPTION
**Pull request by othiman**
Hi.
I fixed some compilation errors on Windows and Linux and added a .gitignore file to unclutter the git status command. This should at least fix #63.

I would be happy if you could include these patches into the dev branch.

Best regards,
Thomas

### CODE REVIEW

**Comment by dennisguse** [comment]
Cool!
It would be great if you could split up the pull request into two separate one: one for .gitignore and one for the build toolchain.
It is easier to discuss then ;)

Two minor thing:
* Almost everywhere in the code base ´#ifdef defined(__unix__) || defined(__unix)´ is used.
Could you change this in the patch?
* Are the g711, pshar, and rpelt working without `unistd.h`?

**Comment by othiman** [comment]
Hi. I cherrypicked the PR and now only the compilation fixes are included.

**Comment by othiman** [comment]
> Two minor thing:
> 
>     * Almost everywhere in the code base ´#ifdef defined(**unix**) || defined(__unix)´ is used.
>       Could you change this in the patch?
Where did you find the above line? I grepped the code for "unix" and most of the time "#if defined (unix)" is used. Maybe we should agree on some definition and then change it everywhere in the code to the same.
> 
>     * Are the g711, pshar, and rpelt working without `unistd.h`?
I do not know. I will try out when I find some time for that.

**Comment by dennisguse** [comment]
@othiman 
My fault.
It is actually: `#ifdef defined(unix) || defined(__unix)`
I added the asterisks as bold formatting.
In addition, the checks are at the moment not done everywhere consistently.
Sometimes, it is only `defined(unix)` or `defined(__unix)` or both.

**Comment by othiman** [comment]
@dennisguse I found a very nice site which addresses this issue:
http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system#HowtodetectPOSIXandUNIX

I think we should use
`#if !defined(_WIN32) && (defined(__unix__) || defined(__unix) || (defined(__APPLE__) && defined(__MACH__)))`
based on the article.

**Comment by othiman** [comment]
Another thing is, what platforms should be supported in the future? E.g., it seems not very reasonable to continue supporting the VMS platform. Anyhow, this PR is outdated, so I close it.

**Pull request closed without merging**
