### PR TITLE
unsup/xdecode: Disabled xencode compilation and regression tests.

### PR DESCRIPTION
**Pull request by ludomal**
Ideally all regression tests should pass before the code is frozen for STL2018 release.

xdecode test vectors fail and it is very likely that xencode will be removed in the next release as it is no longer relevant today (#59).

### CODE REVIEW

**Comment by dennisguse** [comment]
Looks good.
Only question: why not also disable `xdecode`?
And even further: why not removing them?

**Review by dennisguse — DISMISSED** [review]
Looks good to me.
I just would prefer removing them completely...

**Comment by ludomal** [comment]
I did not disabled xencode as it passes the tests... 
We could xencode/xdecode code and test vectors if you prefer. I will try to do this later today. 
The code should be frozen tonight so I can produce the attachment to the Recommendation.

**Comment by ludomal** [comment]
xencode/xdecode is not removed from the repository.

**Review by dennisguse — APPROVED** [review]
Also removed xdecode and xencode from manual (unsup.tex).

Looks good.

**Pull request merged**
