### PR TITLE
add a .gitignore file to prevent that generated files are commited

### PR DESCRIPTION
**Pull request by othiman**

### CODE REVIEW

**Comment by othiman** [comment]
Hi. This is the .gitignore file extracted from #64. I checked it ones again on Linux today and added some LaTeX excludes additionally.
Best regards, Thomas

**Comment by dennisguse** [comment]
I will work on this issue on Wednesday.

**Comment by othiman** [comment]
For reference, a very helpful command to check the .gitignore is given here: https://stackoverflow.com/questions/9320218/how-to-list-files-ignored-by-git-that-are-currently-staged-or-committed.

**Comment by othiman** [comment]
added some more files to ignore produced by xdecode

**Comment by othiman** [comment]
needed to rebase it caused by the force revert push

**Comment by dennisguse** [comment]
That would be my draft.
I added some generic rules, removed the exclusions (e.g., bbl files need to be converted to bib anyhow).
But I must admit, we really need to rework the file suffixes of all these test files.
Just too many differences...
As quick alternative, we could move all test result files into a separate folder (e.g. tests/).
This, however, would require prefixing all tests.

```
#Generic rules
*~
*.bak
*.log
*old
*.org
bin/

#Generated test files
*05g10.*
*.[am]16
*.[am]24
*.[am]32
*.[am]40
*[0-5t].[bfs]er
*.flt
*.hqp
*bin.f*.out
*sptst*
*md[1-3]
*.proc
*c.raw
*.rec
sine*.[aqru]*
sine*.l
!sine*.unx
src/eid/sta
*.smp
!*sample.[LR].32k.1ch.smp
*[0-9].sta
sweep.[aru]*
*temp*
*testg712*
*.tst
!*voic*.tst

src/g722/test_data/inpsp.bs
src/g722/test_data/outsp.e-d
src/g727/test_data/rn54_a.out
src/is54/test_data/voice-pf.bec
src/is54/test_data/voice-pf.rek
src/is54/test_data/voice.bbs
src/is54/test_data/voice.bec
src/is54/test_data/voice.hbs
src/is54/test_data/voice.rek
src/sv56/test_data/voice.prc
src/sv56/test_data/voice.rms
src/unsup/test_data/astrip.blk
src/unsup/test_data/undo.txt
src/utl/test_data/voice.rnp
src/utl/test_data/voice.rou
src/utl/test_data/voice.tru
src/unsup/test_data/v.uue
src/unsup/test_data/v01.uue

#CMake generated files
CMakeCache.txt
CMakeFiles
CMakeScripts
Testing
Makefile
cmake_install.cmake
install_manifest.txt
compile_commands.json
CTestTestfile.cmake

#LaTeX files
*.aux
*.bbl
*.blg
*.fdb_latexmk
*.fls
*.out
*.pdf
*.toc

#Visual Studio
*.suo
*.user
*.userosscache
*.sln.docstates

[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/

.vs/
*vcxproj*
*.sln
```

**Comment by othiman** [comment]
@dennisguse, I in-cooperated most of your proposed changes. I think we should keep the stl2014man.bbl for now till a solution for the missing bib file is found. I would propose to merge this now and have another look at it when all other PRs are also merged.

**Comment by dennisguse** [comment]
@othiman As the bbl file will be removed anyhow (and it can still be modified with git add -f), I would prefer removing the exclusion. The chances are quite high that it will be forgotten to be removed and we added another small piece of complexity.

**Comment by othiman** [comment]
@dennisguse exclusion of stl2014man.bbl is removed now.

**Pull request merged**
